### ISSUE TITLE
Call a method from object

### ISSUE THREAD

**Issue by FlyingOddo** [appsup-dart/expressions#21]
I want to call a method from a self defined object. When I try to call the method, I got the following exception:
ExpressionEvaluatorException (ExpressionEvaluatorException: Access of member `doMyMethod` not supported for objects of type `MyObject`: have you defined a member accessor in the ExpressionEvaluator?)

Is it somehow possible or is it overall not supported?

**Comment by rbellens** [comment]
As reflection is not supported on all platforms and is generally not recommended because it prevents compiler optimizations, it is not possible to implement a generic member accessor. You can however implement a custom `ExpressionEvaluator` and override the `evalMemberExpression` method or use the `memberAccessors` argument of the `ExpressionEvaluator` constructor.
